#pragma once
#include "logical.hpp"
#include "date.hpp"
#include "time.hpp"
#include "datetime.hpp"
#include "timestamp.hpp"
#include "byte.hpp"

#include "natural.hpp"
#include "integer.hpp"
#include "longinteger.hpp"
#include "decimal.hpp"
#include "path.hpp"
#include "nodatatype.hpp"
#include "array.hpp"